login page connected to api
mavidurak/orientation-front-end pull request #37
Opened 2021-07-14 10:13 UTC by bssenoz

2021-07-16 08:45 UTC, saracalihan requested changes

2021-07-16 08:45 UTC, saracalihan commented on src/components/Layout/Navbar.vue
> +        'x-access-token': this.isLogin,
localStorage'dan doğrudan burada okuma yapabilirsin.Bir daha değişkene atama yapmana gerek yok.

2021-07-16 08:45 UTC, saracalihan commented on src/router/index.js
> +  name: 'Login',
Burada `Login` komponentini import etmek yerine yönlendirme yaparak url'in de değişmesini sağlamalısın.

2021-07-30 19:32 UTC, bssenoz commented
![login](https://user-images.githubusercontent.com/71407054/127702994-33c44635-1675-4cfe-bd31-f5eb2a57c500.png)
![register](https://user-images.githubusercontent.com/71407054/127703030-f9e22f27-f5ae-452f-add5-11b6ef645a40.png)

2021-07-30 19:34 UTC, bssenoz commented
![login](https://user-images.githubusercontent.com/71407054/127703216-7537c4f5-ef45-4200-bcdd-061c6302092a.png)
![register](https://user-images.githubusercontent.com/71407054/127703223-0111e00a-04b0-41f5-9468-69ca2b4ab737.png)

2021-07-30 20:20 UTC, bssenoz commented
![login](https://user-images.githubusercontent.com/71407054/127707624-8f220dc4-408b-419a-b0bd-2a0bfe5ce640.png)
![register](https://user-images.githubusercontent.com/71407054/127707631-beeffe56-57ee-4dae-8fc6-d3167be73b2c.png)

2021-07-31 18:33 UTC, saracalihan requested changes

2021-07-31 18:33 UTC, saracalihan commented on src/views/guests/Login.vue
> +    <div class="login-in">
`login-in` typo mu yoksa login sayfasının içi demek mi?Gerekli değişikliği yapınız

2021-07-31 18:33 UTC, saracalihan commented on src/views/guests/Login.vue
> +          name="username"
Form gönderimi yapmayacağımız için `name`  kullanmamıza gerek yok zaten bu inputun değerini `v-model` ile takip edebiliyoruz

2021-07-31 18:33 UTC, saracalihan commented on src/views/guests/Register.vue
> +          name="name"
login sayfasında dediğimiz nedenden dolayı bu sayfadaki tüm `name`'leri kaldırmalısın

2021-07-31 18:33 UTC, saracalihan commented on src/views/guests/Register.vue
> +        <Password @password="password = $event" />
içerden `emit` edilen değeri doğrudan bu sayfadaki bir fonksiyon içine parametre olarak gönderebilirsin. Değer eşitlemesini fonksiyon içinde yapabiliriz.

2021-08-03 09:04 UTC, saracalihan approved these changes
https://github.com/mavidurak/orientation-front-end/pull/42 den sonra merge edilebilir

2021-08-06 18:58 UTC, merged