added tooltip
mavidurak/orientation-front-end pull request #41
Opened 2021-07-30 13:00 UTC by beyzaerkan

2021-07-30 13:04 UTC, beyzaerkan commented
![Screenshot from 2021-07-30 16-01-47](https://user-images.githubusercontent.com/76122007/127656872-29b27299-bfda-4348-80bd-34cdf012dd13.png)

2021-07-31 18:11 UTC, saracalihan requested changes

2021-07-31 18:11 UTC, saracalihan commented on src/router/index.js
> +  component: () => import('../views/home/Explore.vue'),
hangi layout'un kullanılacağını da belirtmelisin

2021-07-31 18:11 UTC, saracalihan commented on src/components/ContentIcon/ContentIconList.vue
> +  name: 'ContentIconList',
`name` değerini en üste yazarsak komponenti anlamak daha kolay olur

2021-07-31 18:11 UTC, saracalihan commented on src/components/ContentIcon/ContentIconList.vue
> +      this.contents = res.data.content;
api bize bir dizi gönderdiği için key ismi tekil olamamalı. `res.data.contents` şeklinde kullanabilmek için api'da gerekli değişiklikleri yapabilirsin.

2021-07-31 18:11 UTC, saracalihan commented on src/components/ContentIcon/ContentIcon.vue
> +
Gereksiz boşluk olmamalı

2021-08-01 14:35 UTC, beyzaerkan commented
![Screenshot from 2021-08-01 17-34-06](https://user-images.githubusercontent.com/76122007/127774742-85b3d1c0-a857-4212-afde-6508a29724f3.png)
![Screenshot from 2021-08-01 17-34-10](https://user-images.githubusercontent.com/76122007/127774748-28c7dbd5-0047-41e5-a3ec-f8429de1832f.png)

2021-08-03 06:58 UTC, saracalihan requested changes

2021-08-03 06:58 UTC, saracalihan commented on src/components/ContentIcon/ContentIconList.vue
> +      return this.contents.filter((item) => item.type === 'MOVIE');
tipleri ileride değişiklik yaptığımızda her yerden elle değişiklik yapmamamk için `src/constants/index.js` içindeki `CONTENT_TEYPES` içinden almalısın

2021-08-06 18:20 UTC, saracalihan approved these changes

2021-08-06 18:21 UTC, merged