content create added
mavidurak/orientation-front-end pull request #64
Opened 2021-08-19 09:33 UTC by Arifkarakilic

![image](https://user-images.githubusercontent.com/72814680/130045653-d08f91da-1cce-479a-a830-d2591d6b1282.png)

2021-08-22 19:42 UTC, saracalihan requested changes

2021-08-22 19:42 UTC, saracalihan commented on src/router/index.js
> +    path: '/contents-create',
`path` değerinin `contents/new` olması daha doğru

2021-08-22 19:42 UTC, saracalihan commented on src/router/index.js
> +    meta: { layout: 'home' },
Kodun son halinde burada isim değişikliği yapıldı

2021-08-22 19:42 UTC, saracalihan commented on src/views/home/ContentCreate.vue
> +          <div></div>
Bu neden var?

2021-08-22 19:42 UTC, saracalihan commented on src/views/home/ContentCreate.vue
> +            placeholder="Name area"
`name area` --> `content name`

2021-08-22 19:42 UTC, saracalihan commented on src/views/home/ContentCreate.vue
> +            id="content_submit_for_52845775"
id burada gereksiz

2021-08-22 19:42 UTC, saracalihan commented on src/views/home/ContentCreate.vue
> +      console.log(          {
porjede `console.log` bulunmamalı

2021-09-09 15:50 UTC, Arifkarakilic commented
why this pr not accepted?

2021-09-10 18:20 UTC, saracalihan approved these changes

2021-09-10 18:20 UTC, merged